# 只保留社交菜单
[[social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/CaiJimmy/hugo-theme-stack"
  [social.params]
    icon = "brand-github"

[[social]]
  identifier = "twitter"
  name = "X"
  url = "https://twitter.com"
  [social.params]
    icon = "brand-twitter"
