[[main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
    [main.params]
        icon = "home"

# --- 以下是新增的二级栏目，全部挂在 home 下面 ---

[[main]]
    parent = "home"      # 锁定父级 ID 为 home
    identifier = "gallery"
    name = "燕山美图"
    url = "/page/gallery/"
    weight = 1

[[main]]
    parent = "home"      # 锁定父级 ID 为 home
    identifier = "featured"
    name = "精品文章"
    url = "/page/featured/"
    weight = 2

[[main]]
    parent = "home"      # 锁定父级 ID 为 home
    identifier = "novel"
    name = "小说连载"
    url = "/page/novel/"
    weight = 3

    # --- 原有的平级栏目保持不变 ---

[[main]]
    identifier = "jiuwu"
    name = "旧物时光"
    url = "/page/jiuwu/"
    weight = 2
    [main.params]
        icon = "shopping-bag"

[[main]]
    identifier = "bbs"
    name = "燕山论坛"
    url = "/page/bbs/"
    weight = 3
    [main.params]
        icon = "messages"

[[main]]
    identifier = "phonebook"
    name = "电话黄页"
    url = "/page/phonebook/"
    weight = 4
    [main.params]
        icon = "phone"

[[main]]
    identifier = "links"
    name = "友情链接"
    url = "/links/"
    weight = 5
    [main.params]
        icon = "link"

# 找回搜索按钮
[[main]]
    identifier = "search"
    name = "站内搜索"
    url = "/search/"
    weight = 6
    [main.params]
        icon = "search"
