[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 2

[[main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 3

[[main]]
    identifier = "links"
    name = "Links"
    url = "/links/"
    weight = 4
