[[main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 10
    [main.params]
        icon = "home"

[[main]]
    name = "Archives"
    identifier = "archives"
    url = "/archives/"
    weight = 20
    [main.params]
        icon = "archive"

[[main]]
    name = "Search"
    identifier = "search"
    url = "/search/"
    weight = 30
    [main.params]
        icon = "search"

[[main]]
    name = "Links"
    identifier = "links"
    url = "/links/"
    weight = 40
    [main.params]
        icon = "link"
